### ISSUE TITLE
ReferenceError: Rooms is not defined

### ISSUE THREAD

**Issue by ThBlackSage** [smogon/pokemon-showdown#10314]
I've had a private server running for about 2 years, and i've now run into this ReferenceError: Rooms is not defined issue followed by a CRASH: Error: IPC channel is already disconnected. The server was running fine until I fetched updates this past week from the master having been about 24 behind at the time. Seeing as how the dist folder is created later and not directly from the repository I'm pretty confused as to the error. I've never made any Rooms related changes or additions.

Sorry for the trouble and I appreciate any help at all.

c:\pokemon-showdown-test>node pokemon-showdown
RESTORE CHATROOM: lobby
RESTORE CHATROOM: staff
Worker 1 now listening on 0.0.0.0:8000
Worker 1 now listening for SSL on port 443
Test your server at http://localhost:8000
c:\pokemon-showdown-test\dist\server\chat-plugins\chatlog.js:796
const LogSearcher = new (Rooms.Roomlogs.table ? DatabaseLogSearcher : (
                    ^

ReferenceError: Rooms is not defined
    at Object.<anonymous> (c:\pokemon-showdown-test\dist\server\chat-plugins\chatlog.js:796:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.17.1

CRASH: Error: IPC channel is already disconnected
    at new NodeError (node:internal/errors:405:5)
    at ChildProcess.target.disconnect (node:internal/child_process:891:26)
    at QueryProcessWrapper.destroy (c:\pokemon-showdown-test\lib\process-manager.ts:203:16)
    at QueryProcessWrapper.release (c:\pokemon-showdown-test\lib\process-manager.ts:189:9)
    at QueryProcessManager.releaseCrashed (c:\pokemon-showdown-test\lib\process-manager.ts:455:16)
    at ChildProcess.<anonymous> (c:\pokemon-showdown-test\lib\process-manager.ts:512:47)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess.emit (node:domain:489:12)
    at finish (node:internal/child_process:921:14)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by mia-pi-git** [comment]
https://github.com/smogon/pokemon-showdown/commit/c6ed617447171ed6b9ecde6d60f2c69a9aefed7c.
