### ISSUE TITLE
CRASH: Error: Cannot find module './driver/client'

### ISSUE THREAD

**Issue by svivian** [smogon/pokemon-showdown#1295]
I am getting this error when running the latest version of Showdown:

```
CRASH: Error: Cannot find module './driver/client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/showdown/test/Pokemon-Showdown/node_modules/sockjs/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver.js:7:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I'm on Node v0.10.25, Ubuntu 14.04. I've run `npm install` of course but something's not right. From the look of the [websocket-driver-node repo](https://github.com/faye/websocket-driver-node/tree/master/lib/websocket) there should be a "driver" folder in the `websocket-driver/lib/websocket/` directory but it's not there on my system.

I've tried doing a completely fresh install of just this repo and still get the same issue. Is there something off with the dependencies? Any ideas?

**Comment by pokemonbattlesimulator** [comment]
why do i keep getting this error module.js:338
    throw err;
please can someone help me with this problem
