### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by Andyloris** [smogon/pokemon-showdown#7737]
Hi I have an issue,
when i run the command node pokemon-showdown,
i have this error: 

Error: Command failed: node build
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at build (C:\Users\Robert\Desktop\top secret\pgmprogamer andy roland\pokemon\ServPS\pokemon-showdown\pokemon-showdown:21:27)
    at Object.<anonymous> (C:\Users\Robert\Desktop\top secret\pgmprogamer andy roland\pokemon\ServPS\pokemon-showdown\pokemon-showdown:40:14)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 22036,
  stdout: null,
  stderr: null
}

**Comment by Andyloris** [comment]
I have just fixed this problem
