### ISSUE TITLE
Build faillure

### ISSUE THREAD

**Issue by Andyloris** [smogon/pokemon-showdown#7738]
Hi,
When i start node pokemon-showdown,
i have this error:

CRASH: Error [ERR_IPC_DISCONNECTED]: IPC channel is already disconnected
    at ChildProcess.target.disconnect (internal/child_process.js:832:26)
    at QueryProcessWrapper.destroy (C:\Users\Robert\Desktop\top secret\pgmprogamer andy roland\pokemon\ServPS\pokemon-showdown\.lib-dist\process-manager.js:178:16)
    at QueryProcessWrapper.release (C:\Users\Robert\Desktop\top secret\pgmprogamer andy roland\pokemon\ServPS\pokemon-showdown\.lib-dist\process-manager.js:164:9)
    at QueryProcessManager.releaseCrashed (C:\Users\Robert\Desktop\top secret\pgmprogamer andy roland\pokemon\ServPS\pokemon-showdown\.lib-dist\process-manager.js:421:16)
    at ChildProcess.<anonymous> (C:\Users\Robert\Desktop\top secret\pgmprogamer andy roland\pokemon\ServPS\pokemon-showdown\.lib-dist\process-manager.js:468:48)
    at ChildProcess.emit (events.js:310:20)
    at ChildProcess.EventEmitter.emit (domain.js:482:12)
    at finish (internal/child_process.js:861:14)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Thanks in advance

**Comment by Zarel** [comment]
It sounds like your OS is having trouble creating child processes. I've never seen this happen before. Did you follow the setup instructions exactly? Is there another error message before that one? Can you provide the full log?

**Comment by Andyloris** [comment]
I've just solved the problem
