### ISSUE TITLE
Error when running the program.

### ISSUE THREAD

**Issue by NotOrca22** [smogon/pokemon-showdown#7770]
I ran npm run build and I got the following error: 
`> pokemon-showdown@0.11.3 build {path of folder}
> node build

ReferenceError: Error transforming config/formats.ts: unexpected is not defined
    at expectContextual (node_modules/sucrase/dist/parser/traverser/util.js:27:5)
    at parseImport (node_modules/sucrase/dist/parser/traverser/statement.js:1075:28)
    at parseStatementContent (node_modules/sucrase/dist/parser/traverser/statement.js:190:9)
    at parseStatement (node_modules/sucrase/dist/parser/traverser/statement.js:108:3)
    at parseBlockBody (node_modules/sucrase/dist/parser/traverser/statement.js:510:5)
    at parseTopLevel (node_modules/sucrase/dist/parser/traverser/statement.js:84:3)
    at parseFile (node_modules/sucrase/dist/parser/traverser/index.js:17:35)
    at parse (node_modules/sucrase/dist/parser/index.js:26:35)
    at getSucraseContext (node_modules/sucrase/dist/index.js:88:30)
    at transform (node_modules/sucrase/dist/index.js:40:28)
child_process.js:669
    throw err;
    ^

Error: Command failed: npx sucrase  -q ./config -d ./.config-dist --transforms typescript,imports --enable-legacy-typescript-module-interop
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at shell (build:19:16)
    at sucrase (build:109:2)
    at Object.<anonymous> (build:113:5)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 66395,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pokemon-showdown@0.11.3 build: `node build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pokemon-showdown@0.11.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-12-06T18_47_19_545Z-debug.log
'

**Comment by Zarel** [comment]
What happens if you `npx tsc`?

**Comment by NotOrca22** [comment]
I got 
'
error TS5014: Failed to parse file 'tsconfig.json': Unexpected token ] in JSON at position 322.
' as the error.

**Comment by Zarel** [comment]
You seem to have accidentally added a `]` to `tsconfig.json` at position 322.

Have you tried reinstalling a fresh copy?

**Comment by NotOrca22** [comment]
Thanks so much Zarel! I've got it up!
