### ISSUE TITLE
Node.js server not starting 

### ISSUE THREAD

**Issue by haasj22** [smogon/pokemon-showdown#8760]
I get an issue when I do ./pokemon-showdown as follows:

CRASH: Error: ENOENT: no such file or directory, chmod '/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/logs/repl/sim-11021'
    at Object.chmodSync (fs.js:1224:3)
    at Server.<anonymous> (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/repl.ts:114:8)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:485:12)
    at emitListeningNT (net.js:1348:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

CRASH: Error: ENOENT: no such file or directory, chmod '/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/logs/repl/chat-db'
    at Object.chmodSync (fs.js:1224:3)
    at Server.<anonymous> (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/repl.ts:114:8)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:485:12)
    at emitListeningNT (net.js:1348:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)

Error: ENOENT: no such file or directory, chmod '/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/logs/repl/team-validator-11010'
    at Object.chmodSync (fs.js:1224:3)
    at Server.<anonymous> (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/repl.ts:114:8)
    at Object.onceWrapper (events.js:421:28)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:485:12)
    at emitListeningNT (net.js:1348:10)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/logs/repl/team-validator-11010'
}

CRASH: Error [ERR_IPC_DISCONNECTED]: IPC channel is already disconnected
    at ChildProcess.disconnect (internal/child_process.js:861:26)
    at QueryProcessWrapper.destroy (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/process-manager.ts:204:16)
    at QueryProcessWrapper.release (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/process-manager.ts:190:9)
    at QueryProcessManager.releaseCrashed (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/process-manager.ts:458:16)
    at ChildProcess.<anonymous> (/Users/johnhaas/Dropbox/My Mac (John’s MacBook Pro)/Downloads/pokemon-showdown-master/lib/process-manager.ts:515:47)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at finish (internal/child_process.js:891:14)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

I've used different versions of node.js but I seem to keep running into this issue. Because of this, it will not let me connect to the localhost server. Any ideas?

**Comment by jaysnel** [comment]
Interesting, I get this same error as well when running it, but mine gives me 3 of these errors and then works but then slows down my pc. If i then visit the site locally, it completely freezes my pc

**Comment by haasj22** [comment]
No mine does this starts, and then repeats the previous errors. If I go onto the site it shows the layout, but won't actually let me connect to the server. It sounds like you have a similar error, but I have not found a fix. I've tried lots of different versions of node.js but nothing seems to fix it.

**Comment by haasj22** [comment]
I found a solution to my problem. If I turn repl to false in my config.ts, and do npm install, the problem resolves itself. I plan to close this issue and open a new one with a title and comment that more accurately explains the issue.
