### ISSUE TITLE
ReferenceError: BattleReady is not defined

### ISSUE THREAD

**Issue by svivian** [smogon/pokemon-showdown#8823]
When running the server I get this error:

```
.../app/server/ladders.ts:503
	BattleReady,
 ^
ReferenceError: BattleReady is not defined
    at Object.<anonymous> (.../app/server/ladders.ts:503:2)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module.m._compile (.../app/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Object.require.extensions.<computed> [as .ts] (.../app/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at setupGlobals (.../app/server/index.ts:99:20)
```

Currently using node v18.4.0 (npm v8.13.1) but I've tried with v16 and the same issue occurs. I set up a completely fresh install to test it as well but still the same error. Can't really see what the issue could be, since 'BattleReady' is imported at the beginning of that file.

**Comment by BUCKFAE** [comment]
Hi, #8824 might help you.
