### ISSUE TITLE
ERR_IPC_Disconnected / IP Tools not defined

### ISSUE THREAD

**Issue by ThBlackSage** [smogon/pokemon-showdown#9160]
I've been getting these error messages after having my server up for about 2hrs everytime.
I've looked through past issues to see if any of their fixes for similar issues applied but none seemed to work. 
I'm running the server off a spare Win10 computer with nothing else on it other than internet browsers.
I appreciate any help possible.

CRASH: ReferenceError: IPTools is not defined
    at Object.clean (c:\pokemon-showdown\server\monitor.ts:155:3)
    at Timeout._onTimeout (c:\pokemon-showdown\server\monitor.ts:357:51)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)

c:\pokemon-showdown\server\monitor.ts:61
        Rooms.global.reportCrash(error, source);
        ^

ReferenceError: Rooms is not defined
    at Object.crashlog (c:\pokemon-showdown\server\monitor.ts:89:3)
    at process.<anonymous> (c:\pokemon-showdown\server\chat.ts:2675:11)
    at process.emit (node:events:525:35)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (c:\pokemon-showdown\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
    at process._fatalException (node:internal/process/execution:159:25)

Node.js v19.2.0

CRASH: Error [ERR_IPC_DISCONNECTED]: IPC channel is already disconnected
    at new NodeError (node:internal/errors:393:5)
    at ChildProcess.disconnect (node:internal/child_process:898:26)
    at QueryProcessWrapper.destroy (c:\pokemon-showdown\lib\process-manager.ts:204:16)
    at QueryProcessWrapper.release (c:\pokemon-showdown\lib\process-manager.ts:190:9)
    at SQLDatabaseManager.releaseCrashed (c:\pokemon-showdown\lib\process-manager.ts:458:16)
    at ChildProcess.<anonymous> (c:\pokemon-showdown\lib\process-manager.ts:515:47)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at finish (node:internal/child_process:928:14)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by MathyFurret** [comment]
I was having this issue too, but it should be fixed on latest master.
